--1.Count thr distinct number of products.
SELECT 
  COUNT(NO_PRODUTO) 
FROM 
  DADOS_ABERTOS_COSMETICO
  
--71.074 products.

--2.Searching the products related to ACNE.

SELECT 
  COUNT(NO_PRODUTO)
FROM 
  DADOS_ABERTOS_COSMETICO
WHERE 
   NO_PRODUTO LIKE '%ACNE%'
OR NO_PRODUTO LIKE '%ESPINHA%'

--736 products, which is less than 1%.

--3.Searching adesivos para acne.

SELECT 
  NO_PRODUTO
FROM 
  DADOS_ABERTOS_COSMETICO 
WHERE 
  NO_PRODUTO LIKE '%ADESIVO%'

--One product was found: O BOTICARIO ADESIVOS SECATIVOS PARA ACNE.

--4.Analysing the companies producing most of the acne products.

SELECT 
NO_RAZAO_SOCIAL_EMPRESA,
COUNT(DISTINCT NO_PRODUTO)
FROM
(SELECT 
 NO_RAZAO_SOCIAL_EMPRESA,
 NO_PRODUTO
FROM 
  DADOS_ABERTOS_COSMETICO1 
WHERE
   NO_PRODUTO LIKE '%ACNE%'
OR NO_PRODUTO LIKE '%ESPINHA%'
OR NO_PRODUTO LIKE '%ADESIVO')
GROUP BY 
NO_RAZAO_SOCIAL_EMPRESA

--172 companies total.

/*
TOP 20
VALMARI-LABORATORIOS DERMOCOSMETICOS LTDA	38
BOTICA COMERCIAL FARMACEUTICA LTDA.	22
ALIANZA INDUSTRIA E COMERCIO DE COSMEETICOS LTDA EPP	21
BIO SCIENTIFIC INDUSTRIA DE COSMETICOS LTDA EPP	18
CASA SIENA FRAGR�NCIAS LTDA - EPP	13
INDUSTRIAL E COMERCIAL BELLA PLUS LTDA	13
JOHNSON & JOHNSON INDUSTRIAL LTDA.	13
MAGISTRIS DO BRASIL LABORATORIO DERMOCOSMETICO LTDA - EPP	13
BIOLAB DERMOCOSMETICOS LTDA.	12
COSMEX - EXCELENCIA EM COSMETICOS LTDA	12
LIPSON COSMETICOS LTDA	12
NATURELLE IND E COMERCIO DE PRODUTOS NATURAIS LTDA	12
PROCOSA PRODUTOS DE BELEZA LTDA	11
AVON INDUSTRIAL LTDA	10
BIOPELE IND COM LTDA	10
COSMETICA INDUSTRIAL BRENNER LTDA	10
LABORATORIOS STIEFEL LTDA	10
BEIERSDORF INDUSTRIA E COMERCIO LTDA	9
NOBILE INDUSTRIA, COMERCIO E BENEFICIAMENTO LTDA	9
NATIVA BIOCOSMETICOS INDUSTRIA E COMERCIO LTDA	8
*/
